# Generated by Django 5.1.3 on 2024-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'computers'), ('fashion', 'Fashion'), ('home', 'Home & Living'), ('books', 'Books'), ('others', 'Others')], max_length=50),
        ),
    ]
